-- AlterEnum
ALTER TYPE "leaderType" ADD VALUE 'CHAIR_HACKATHON';
ALTER TYPE "leaderType" ADD VALUE 'CHAIR_PLACEMENT';
ALTER TYPE "leaderType" ADD VALUE 'CHAIR_COMMUNICATIONS';
ALTER TYPE "leaderType" ADD VALUE 'DELEGATE_PGC';
ALTER TYPE "leaderType" ADD VALUE 'DELEGATE_NATIONALS';
